server {
    listen 80;

    location = / {
        default_type text/plain;
        return 200 'Fallback Host';
    }

    location = /custom {
        default_type text/plain;
        return 200 'custom 1';
    }

    location = /custom/ {
        default_type text/plain;
        return 200 'custom 1';
    }

    location = /custom2 {
        default_type text/plain;
        return 200 'custom 2';
    }

    location = /custom2/ {
        default_type text/plain;
        return 200 'custom 2';
    }

}
